#!/bin/bash

STAGE=$1

if [ -z "$STAGE" ];
then
    echo "Usage: $0 STAGE"
    exit 1
fi

DIR=`dirname $0`

cp $DIR/$STAGE/zipbase64_1.0.0.html ../$DIR/en/
cp $DIR/$STAGE/zipbase64_1.0.0+ru.html ../$DIR/ru/
